apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: juice-shop-ui
  template:
    metadata:
      labels:
        app: juice-shop-ui
    spec:
      containers:
      - image: bkimminich/juice-shop
        name: juice-shop
        ports:
        - containerPort: 3000
